SEND_SMS_TOKEN_EXPIRES = 60*10

#短信验证码在redis有效时间
SMS_CODE_REDIS_EXPIRES = 60*10

#短信发送标志
SEND_SMS_CODE_INTERVAL = 60
#用户地址数量
USER_ADDRESS_COUNTS_LIMIT= 10
#最大用户浏览历史记录
USER_BROWSING_HISTORY_COUNTS_LIMIT = 5